# Generated by Django 5.1 on 2024-09-20 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_manufacturer_city_manufacturer_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.manufacturer'),
        ),
    ]
