# Generated by Django 5.1 on 2024-09-20 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_medicine_manufacturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expire_date', models.DateField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
            ],
            options={
                'unique_together': {('medicine',)},
            },
        ),
    ]
