# Generated by Django 5.1 on 2024-09-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='med_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
