# Generated by Django 5.1 on 2024-09-21 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.doctor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('pres_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('doc_id', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.doctor')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
            ],
        ),
    ]
