# Generated by Django 5.1 on 2024-09-23 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='med_id',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
        migrations.CreateModel(
            name='MedDetails',
            fields=[
                ('med_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
                ('pres_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='med_details', to='users.prescription')),
            ],
        ),
    ]
