# Generated by Django 5.1 on 2024-09-23 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_prescription_med_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(default='CASH', max_length=50),
        ),
    ]
