# Generated by Django 5.1 on 2024-09-23 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_bill_payment_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.manufacturer')),
                ('med_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.medicine')),
            ],
        ),
    ]
